name: Compatibility Report
description: Report the compatibility status of a game on FreeMyXe.
title: "[Compatibility] Title"
labels: ["compatibility", "game report"]
body:
  - type: markdown
    attributes:
      value: "## Please fill out the following details to help the community."
  
  - type: input
    id: title
    attributes:
      label: "Title"
      description: "Enter the full name of the Game or Homebrew."
      placeholder: "e.g., Sonic Generations"

  - type: dropdown
    id: game-region
    attributes:
      label: "Region"
      description: "Select the game's region."
      options:
        - NTSC-U (USA)
        - PAL (Europe)
        - NTSC-J (Japan)
        - World
        - Other
        - Homebrew

  - type: dropdown
    id: compatibility-status
    attributes:
      label: "Does the game work?"
      options:
        - ✅ Works (Fully functional)
        - ⚠️ Partially (Works but has issues)
        - ❌ Borked (Does not work)

  - type: checkboxes
    id: patched-xex
    attributes:
      label: "Have you made sure to patch the XEX file first before running it?"
      description: "Make sure you've used XePatcher/XexTool before reporting an issue."
      options:
        - label: "Yes, I definitely have patched the XEX file."
        - label: "No (why would you click this)"

  - type: textarea
    id: notes
    attributes:
      label: "Notes"
      description: "Describe any issues, fixes, or observations."
      placeholder: "Example: Game crashes after intro, but works with a patch made for RGH: example.com."

  - type: textarea
    id: logs
    attributes:
      label: "Logs or Error Messages (if available)"
      description: "Paste any logs, error messages, or debug output."
      placeholder: "Example: Fatal crash at 0xXXXXXXXX."
