name: Compatibility Report
description: Report the compatibility status of software on FreeMyXe.
title: "[Compatibility] Title"
labels: ["compatibility", "Game report"]
body:
  - type: markdown
    attributes:
      value: "## Please fill out the following details to help the community."

  - type: input
    id: title
    attributes:
      label: "Title"
      description: "Enter the full name of the Game or Homebrew."
      placeholder: "e.g., Sonic Generations"

  - type: dropdown
    id: type
    attributes:
      label: "What type of software is this?"
      options:
        - Disc/ISO (Extracted Format - XeX)
        - GoD (Container Format)
        - GoD (Extracted Format - XeX)
        - GoD (Iso2God Container Format) 
        - Xbox Live Arcade
        - Homebrew (XEX/ELF)
        - Patch (XEX)

  - type: dropdown
    id: compatibility-status
    attributes:
      label: "Does the title work?"
      options:
        - ✅ Works (Fully functional)
        - ⚠️ Partially (Works but has issues)
        - ❌ Borked (Does not work)

  - type: checkboxes
    id: patched-xex
    attributes:
      label: "Have you made sure to patch the files first before running it?"
      description: "Make sure you've used one of the available methods before reporting an issue."
      options:
        - label: "Yes, I definitely have patched the XEX file and any other necessary files or unlocked the GoD."
        - label: "No (some titles and XBLA)"

  - type: dropdown
    id: method
    attributes:
      label: "Which method did you use?"
      options:
        - Manual Patching
        - XexTool
        - GoD/XBLA Patching

  - type: checkboxes
    id: updates-removed
    attributes:
      label: "Title Update Specifications"
      description: "Did you apply any Title Updates for this Game?"
      options:
        - label: "Base Game - No Title Update Installed"
        - label: "Title Update Installed"
        - label: "I Had To Remove a Title Update For The Game To Work"
        - label: "Does Not Apply (Homebrew)"

  - type: checkboxes
    id: Homebrew-elf
    attributes:
      label: "Homebrew ELF Format"
      description: "Some Homebrew applications may not work correctly on certain Xbox 360 motherboard revisions (Corona or Winchester). Applications pre-2013 may also have compatibility issues."
      options:
        - label: "Yes, this is an ELF-formatted Homebrew application"
        - label: "No"

  - type: textarea
    id: notes
    attributes:
      label: "Notes"
      description: "Describe any issues, fixes, or observations."
      placeholder: "Example: Game crashes after intro, but works with a patch made for RGH: example.com."

  - type: textarea
    id: logs
    attributes:
      label: "Logs or Error Messages (if available)"
      description: "Paste any logs, error messages, or debug output."
      placeholder: "Example: Fatal crash at 0xXXXXXXXX."
