name: Compatibility Report
description: Report the compatibility status of a game on FreeMyXe.
title: "[Compatibility] Title"
labels: ["compatibility", "game report"]
body:
  - type: markdown
    attributes:
      value: "## Please fill out the following details to help the community."
  
  - type: input
    id: title
    attributes:
      label: "Title"
      description: "Enter the full name of the Game or Homebrew."
      placeholder: "e.g., Sonic Generations"

  - type: dropdown
    id: type
    attributes:
      label: "What type of application is this?"
      options:
        - Homebrew (XEX/ELF)
        - Game (XEX)
        - GoD
        - XBLA

  - type: dropdown
    id: compatibility-status
    attributes:
      label: "Does the title work?"
      options:
        - ✅ Works (Fully functional)
        - ⚠️ Partially (Works but has issues)
        - ❌ Borked (Does not work)

  - type: checkboxes
    id: patched-xex
    attributes:
      label: "Have you made sure to patch the files first before running it?"
      description: "Make sure you've used one of the available methods before reporting an issue."
      options:
        - label: "Yes, I definitely have patched the XEX file and any other necessary files.."
        - label: "No (some XBLA titles)"

  - type: dropdown
    id: method
    attributes:
      label: "Which method did you use?"
      options:
        - Manual Patching
        - XexTool
        - GoD/XBLA Patching

  - type: checkboxes
    id: updates-removed
    attributes:
      label: "Did you need to remove Title Updates first"
      description: "If you haven't tried and it's partial/borked, don't worry. Someone else can try it, or you can later."
      options:
        - label: "Yes"
        - label: "No"
        - label: "This is homebrew."

  - type: textarea
    id: notes
    attributes:
      label: "Notes"
      description: "Describe any issues, fixes, or observations."
      placeholder: "Example: Game crashes after intro, but works with a patch made for RGH: example.com."

  - type: textarea
    id: logs
    attributes:
      label: "Logs or Error Messages (if available)"
      description: "Paste any logs, error messages, or debug output."
      placeholder: "Example: Fatal crash at 0xXXXXXXXX."
